# Site settings
title: "Mapping the Doctrine of Discovery"
description: "A story of Extraction, Enslavement and Exploitation."
podcast-description: "This podcast explores the history and consequences of the Doctrine of Discovery. Tracking how it was used to exploit Indigenous nations, extract natural resoruces, and  enslave peoples from around the world.
The Doctrine of Discovery is still active in today's governments."
url:  "https://zen-bartik-071847.netlify.app" # Actual base url of the website
#baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Indigenous Values Initiative"
  email: "info@indigenousvalues.org"
  url: "https://doctrineofdiscovery.org/"
permalink: pretty
permalink: /:categories/:title/
keywords: [podcast, doctrine of discovery, Indigenous, native american, first nations]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: indigenousVI
  card: summary
facebook:
  app_id:
logo: /assets/img/logo-demo.jpg
social:
  name: Indigenous Values Initiative
  links:
    - https://www.facebook.com/Doctrine-of-Discovery-115693763603203
    - https://twitter.com/indigenousVI
    - https://doctrineofdiscovery.org/
lang: en

#feed:
  path: feed.xml

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
#podcast_title: Mapping the Doctrine of Discovery
#podcast_author: Indigenous Values Initiative
#podcast_email: info@indigenousvalues.org
#podcast_subtitle: "A Jekyll Theme designed for Podcasters"
#podcast_summary: "A Jekyll Theme designed for Podcasters. This is your podcast's summary."
#podcast_description: "A Jekyll Theme designed for Podcasters. This is your podcast's description."
#podcast_explicit: "no"
#podcast_type: serial
#podcast_lang: en
#podcast_launch: "2019-07-20" #Launch date of your podcast
#podcast_copyright: "&#xA9;Alessio Franceschi"
#podcast_feed:
#podcast_artwork: "/assets/img/Podcast_Cover.png"
