#Site settings
title: "Mapping the Doctrine of Discovery"
description: "A story of Extraction, Enslavement and Exploitation."
podcast-description: "This podcast explores the history and consequences of the Doctrine of Discovery. Tracking how it was used to exploit Indigenous nations, extract natural resoruces, and  enslave peoples from around the world.
The Doctrine of Discovery is still active in today's governments."
url:  "https://zen-bartik-071847.netlify.app" # Actual base url of the website
#baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Indigenous Values Initiative"
  email: "info@indigenousvalues.org"
  url: "https://doctrineofdiscovery.org/"
permalink: pretty
keywords: [podcast, doctrine of discovery, Indigenous, native american, first nations]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed, jekyll-include-cache]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: indigenousVI
  card: summary
facebook:
  app_id:
logo: /assets/img/Podcast_Cover.jpg
social:
  name: Indigenous Values Initiative
  links:
    - https://www.facebook.com/Doctrine-of-Discovery-115693763603203
    - https://twitter.com/indigenousVI
    - https://doctrineofdiscovery.org/
lang: en
